local list = {}

list = {
   {"vergi","tax" },
   {"pulsuz","free" },
   {"maaş","salary"},
   {"hökumət", "gouverment"},
   {"minnoş","cute" },
   {"balam","my baby" },
   {"yaxşıyam","I am fine" },
   {"bəli","yes" },
   {"çox sağol","Thank you" },
   {"hələlik","goodbye" },
   {"tualet hardadır","where is the toilet" },
   {"düz gedin","go straight" },
   {"sola dön","turn left" },
   {"sağa dön","turn right" },
   {"avtobus və qatar"," bus and train" },
   {"öpürəm səni","I kiss you" },
   {"Bütün","Whole"},
   {"Qürur","Proud"},
   {"Onda", "then"},
   {"otaq","room"},
   {"inanmaq","believe" },
   {"hiss edirəm","feel" },
   {"hiss","feeling" },
   {"haqqında","about" },
   {"vəhşi","wild" },
   {"insan","human" },
   {"ruh","spirit" },
   {"doğurdan","really" },
   {"zarafat edirəm","i am joking" },
   {"sakit","calm" },
   {"sakit okean","pacific ocean" },
   {"kino","movie"},
   {"uğurlar","good Luck" },
   {"Xoş gördük","good to see you" },
   {"kim","who" },
   {"dəftər","notebook" },
   {"kilsə","church" },
   {"et","do" },
   {"ola bilər","maybe" },
   {"tez","early" },
   {"gec","late" },
   {"tezliklə","soon" },
   {"Soyuq","Cold" },
   {"Isti","Hot" },
   {"Yemək","Food" },
   {"şad oldum","nice to meet you" },
 }


 return list

