#!/bin/bash
# Script that will run my Azla Gui
# Used to practise azerbajani
# But techincally you can use it for any language
# Keep in mind tho that you need to add words manually

LOCATION="/opt/azla"

cd $LOCATION

if [ "$1" = "--term" ]; then

  exec $LOCATION/rc.lua --term
  
else 

  exec $LOCATION/rc.lua

fi
