local wordlist = {
	{ "armud", "pear" },
	{ "portağal", "orange" },
	{ "limon", "Lemon" },
	{ "Banan", "banana" },
	{ "Qarpız", "watermelon" },
	{ "üzüm", "grape" },
	{ "çiyələk", "strawberry" },
	{ "gilas", "cherry" },
	{ "gilənar", "small cherry" },
	{ "saftalı", "peach" },
	{ "mango", "mango" },
	{ "kakos", "coconut" },
	{ "kivi", "kiwi" },
	{ "qarğidali", "corn" },
	{ "düyü", "rice" },
	{ "makaron", "pasta" },
	{ "balıq", "fish" },
	{ "səhər yeməyi", "breakfast" },
	{ "nahar", "lunch" },
	{ "şam yeməyi", "dinner" },
	{ "qəlyanaltı", "snack" },
	{ "yemək", "meal" },
	{ "ic", "beverage" },
	{ "şirə", "juice" },
	{ "makaron", "pasta" },
	{ "salat", "salad" },
	{ "ət", "meat" },
	{ "kərə yağı", "butter" },
	{ "duz", "salt" },
	{ "un", "flour" },
}

return wordlist
