local wordlist = {
	{ "aş", "head" },
	{ "Qulaq", "ear" },
	{ "Saç", "hair" },
	{ "Ağız", "Mouth" },
	{ "Burun", "Nose" },
	{ "Göz", "Eye" },
	{ "Ağ ciyər", "lungs" },
	{ "Qara ciyər", "liver" },
	{ "Sırğa", "neck" },
	{ "Qollar", "arms" },
	{ "Qoşa", "shoulders" },
	{ "Dirəklər", "elbows" },
	{ "Əllər", "hands" },
	{ "Bədən", "body" },
	{ "Göğs", "chest" },
	{ "Qarn", "stomach" },
	{ "Bel", "waist" },
	{ "Göbələk", "hips" },
	{ "Qəfəs", "ribcage" },
	{ "Sümük", "phlegm" },
	{ "Ürək", "heart" },
	{ "Bədən", "body" },
	{ "Kürək", "knee" },
	{ "Bədən", "body" },
	{ "Ayaq", "foot" },
	{ "Bədən", "body" },
}

return wordlist
