local wordlist = {
    { "Rənglər", "Colors" },
    { "Qırmızı", "Red" },
    { "Qara", "Black" },
    { "Sarı", "Yellow" },
    { "Yaşıl", "Green" },
    { "Bənövşəyi", "Purple" },
    { "Mavi", "Blue" },
    { "Narıncı", "Orange" },
    { "Boz", "Grey" },
    { "Qəhvəyi", "Brown" },
    { "Çəhrayı", "Pink" },
    { "Göy", "Dark blue" },
    { "Ağ", "White" },
    { "Həşər", "Maroon" },
    { "Tünd qırmızı", "Dark red" },
    { "Zövqəng", "Cyan" },
    { "Gümüşü", "Silver" },
    { "Mərcanı", "Coral" },
    { "Kəhrəba", "Olive" },
    { "Mürd", "Mauve" },
    { "Bozçalı", "Ashen" },
    { "Nacar", "Pearl" },
}

return wordlist
