local wordlist = {}

wordlist = {
{ "Yeməkler", "food"},
{ "Pomidor", "tomato"}, 
{ "Xiyar", "cucumber"}, 
{ "Kartof", "potato"}, 
{ "Bibər", "pepper"},
{ "Badımcan", "aubergine"}, 
{ "Kök", "carrot"},
{ "Lobya", "bean"},
{ "Noxud", "pea"}, 
{ "Soğan", "onion"},
{ "Sarımsaq", "garlic"},
{ "Zeytun", "olive"},
{ "Pendir", "cheese"},
{ "Şor", "cottage cheese"}, 
{ "Yumurta ", "egg"},
{ "Ət", "meat"},
{ "Süd", "milk"},
{ "Çay", "tea"},
{ "Kofe", "coffee"},
{ "Sok",  "juice"}, 
{ "Şərab", "wine"}, 
{ "Pivə", "beer"}, 
{ "Şampan ", "champagne"},
{ "Buz", "ice"},
{ "Bal", "honey"},
{ "Su", "water"},
{ "Brokoli", "Broccoli"}, 
{ "Ananas", "Pineapple"}, 
{ "Alma", "apple"},
{ "Armud", "pear"}, 
{ "Portağal", "orange"},
{ "Limon", "Lemon"}, 
{ "Banan", "banana"},
{ "Qarpız", "watermelon"}, 
{ "Üzüm", "grape"},
{ "Çiyələk", "strawberry"}, 
{ "Gilas", "cherry"},
{ "Gilənar", "small cherry"},
{ "Şaftalı", "peach"},
{ "Mango", "mango"}, 
{ "Kakos", "coconut"}, 
{ "Kivi", "kiwi"}, 
{ "Qarğidali", "corn"}, 
{ "Düyü", "rice"}, 
{ "Makaron", "pasta"},
{ "Balıq", "fish"}, 
{ "Toyuq", "chicken"}, 
{ "Mal əti", "beef"}, 
{ "Donuz əti", "pork"},
 }

 return wordlist
