-- Some numbers in azerbajani
local wordlist = {
	{ "bir", "One" },
	{ "iki", "Two" },
	{ "üç", "Three" },
	{ "dörd", "Four" },
	{ "beş", "Five" },
	{ "alti", "Six" },
	{ "yeddi", "Seven" },
	{ "səkkiz", "Eight" },
	{ "doqquz", "Nine" },
	{ "on", "Ten" },
	{ "iyirmi", "Twenty" },
	{ "otuz", "Thirty" },
	{ "qirx", "Fourty" },
	{ "əlli", "Fifty" },
	{ "altmiş", "Sixty" },
	{ "yetmiş", "Seventy" },
	{ "səksən", "Eighty" },
	{ "doxsan", "Ninety" },
	{ "yüz", "Hundred" },
	{ "min", "Thousand" },
	{ "bir million", "million" },
	{ "bu gün", "today" },
	{ "sabah", "tomorrow" },
	{ "dünən", "yesterday" },
	{ "həftə", "week" },
	{ "ay", "month" },
	{ "il", "year" },
	{ "onillik", "decade" },
	{ "əsr", "century" },
	{ "minillik", "millennium" },
}

return wordlist
