local wordlist = {
   { "uğurlar", "good Luck" },
   { "xoş gördük", "good to see you" },
   { "şad oldum", "nice to meet you" },
   { "tualet hardadır", "where is the toilet" },
   { "hələlik", "goodbye" },
   { "avtobus və qatar", "bus and train" },
   { "şad oldum", "nice to meet you" },
   { "Sabahınız xeyir", "Good morning" },
   { "Günaydın", "Good day" },
   { "Axşamınız xeyir", "Good evening" },
   { "Gecəniz xeyir", "Good night" },
   { "Sağ olun", "Thank you" },
   { "Çox sağ ol", "Thank you very much" },
   { "Zəhmət olmasa", "Please" },
   { "Bağışlayın", "Excuse me" },
   { "Necəsiz?", "How are you?" },
   { "Yaxşıyam sağ ol", "I'm fine, thank you" },
   { "Sağ olun yaxşıyam", "Thank you, I'm fine" },
   { "Nə var?", "What's wrong?" },
   { "Nə var necəsiz?", "What's wrong, how are you?" },
   { "Həmişə səhər yaxşı deyiləm", "I'm never good in the morning" },
   { "Bağışlayın haradadır meydan?", "Excuse me, where is the square?" },
   { "Bu necə deyil?", "How much is this?" },
   { "Mən bu dil bilmirəm", "I don't speak this language" },
   { "Sən mənim adımı çox görmüsən?", "Have you seen me before?" },
}

return wordlist
