-- Some verbs thats useful to know
local wordlist = {
	{ "Bağlamaq", "To close" },
	{ "Başa duşmək", "To understand" },
	{ "Başlamaq", "To start" },
	{ "Yazmaq", "To write" },
	{ "Baxmaq", "To look" },
	{ "Göturmaq", "To take" },
	{ "Bilmək", "To know" },
	{ "Getmək", "To go" },
	{ "Gəlmək", "To come" },
	{ "Işlemək", "To work" },
	{ "Səyahət etmək", "To travel" },
	{ "Öyrənmək", "To learn" },
	{ "Oxumaq", "To read" },
	{ "Yemək", "To eat" },
	{ "Içmək", "To drink" },
	{ "Açmaq", "To open" },
	{ "Vermək", "To give" },
	{ "Görmək", "To see" },
	{ "Oynamaq", "To play" },
	{ "Oyanmaq", "To wake up" },
	{ "Dincəlmek", "To rest" },
	{ "Almaq", "To buy" },
	{ "Bilmək", "To know" },
	{ "Yumaq", "To wash" },
	{ "Olmaq", "To be" },
	{ "Ağlamaq", "To cry" },
	{ "Unutmaq", "To forget" },
	{ "Gəzmək", "To walk" },
	{ "Etmək", "To do" },
	{ "Başlamaq", "To start" },
	{ "Bağlamaq", "To close" },
	{ "Qurtarmaq", "To end" },
	{ "Qulaq asmaq", "To listen" },
	{ "Fikirleşmək", "To think" },
	{ "Gətirmək", "To bring" },
	{ "Soruşmaq", "To ask" },
	{ "Zəng vurmaq", "To call" },
	{ "Gözləmək", "To wait" },
	{ "Arzulamaq", "To wish" },
	{ "Ümid etmək", "To hope" },
	{ "Göndərmək", "To send" },
	{ "Tanış olmaq", "To meet" },
	{ "Görüşmək", "To meet up" },
	{ "Xatırlamaq", "To remeber" },
	{ "Zarafat etmək", "To joke" },
	{ "Iyləmək", "To smell" },
}

return wordlist
