local wordlist = {
	{ "kilsə", "church" },
	{ "məbəd", "temple" },
	{ "heyvanxana", "zoo" },
	{ "akvarium", "aquarium" },
	{ "dağlar", "mountains" },
	{ "dərə, vadi", "valley" },
	{ "çöl", "prairie" },
	{ "təpə", "hill" },
	{ "kanyon", "canyon" },
	{ "vulkan", "volcano" },
	{ "okean", "ocean" },
	{ "gölməçə", "pond" },
	{ "axın", "stream" },
	{ "bahar", "spring" },
	{ "şəlalə", "waterfall" },
	{ "mağara", "cave" },
	{ "dune", "dune" },
	{ "çəmən", "meadow" },
	{ "meyvə bağı", "orchard" },
	{ "üzümbağı", "vineyard" },
	{ "ferma", "farm" },
	{ "kənd", "village" },
	{ "şəhər", "town" },
	{ "ölkə", "country" },
	{ "qitə", "continent" },
	{ "torpaq", "earth" },
	{ "ay", "moon" },
	{ "günəş", "sun" },
	{ "ulduz", "star" },
	{ "qalaktika", "galaxy" },
	{ "kainat", "universe" },
	{ "səhər", "morning" },
	{ "axşam", "evening" },
	{ "günorta", "afternoon" },
	{ "gecə", "night" },
	{ "Günəşin doğuşu", "sunrise" },
	{ "Gun batisi", "sunset" },
	{ "gecə yarısı", "midnight" },
	{ "klinika", "clinic" },
	{ "aptek", "pharmacy" },
	{ "həkim", "doctor" },
	{ "tibb bacısı", "nurse" },
	{ "dərman", "medicine" },
	{ "xəstə", "patient" },
	{ "sağlamlıq", "health" },
	{ "xəstəlik", "illness" },
	{ "zədə", "injury" },
	{ "ağrı", "pain" },
	{ "müalicə", "treatment" },
	{ "sağalma", "recovery" },
	{ "qəbul", "appointment" },
	{ "universitet", "university" },
	{ "tələbə", "student" },
	{ "müəllim", "teacher" },
	{ "sinif otağı", "classroom" },
	{ "ev tapşırığı", "homework" },
	{ "imtahan", "exam" },
	{ "degree", "dərəcə" },
	{ "diploma", "diploma" },
	{ "education", "təhsil" },
	{ "lesson", "dərs" },
	{ "question", "sual" },
	{ "answer", "cavab" },
	{ "subject", "fənn" },
	{ "office", "ofis" },
	{ "meeting", "toplantı" },
	{ "project", "layihə" },
}

return wordlist
