local wordlist = {

	{ "pəncərə", "window" },
	{ "əlaqə", "relationship" },
	{ "achar", "key" },
	{ "güzgü", "mirror" },
	{ "yastiq", "pillow" },
	{ "vergi", "tax" },
	{ "maaş", "salary" },
	{ "hökumət", "gouverment" },
	{ "düz gedin", "go straight" },
	{ "otaq", "room" },
	{ "insan", "human" },
	{ "ruh", "spirit" },
	{ "ola bilər", "maybe" },
	{ "dəftər", "notebook" },
	{ "kino", "movie" },
	{ "sakit okean", "pacific ocean" },
	{ "hökumət", "gouverment" },
	{ "Gün", "Day" },
	{ "Kitab", "Book" },
	{ "Masa", "Table" },
	{ "Qapı", "Door" },
	{ "Təyyarə", "Plane" },
	{ "Qurşu", "Bread" },
	{ "Qələm", "Pen" },
	{ "Uşaq", "Child" },
	{ "Bağ", "Garden" },
	{ "Şəhər", "City" },
	{ "Meyvə", "Fruit" },
	{ "Dərə", "Valley" },
	{ "Yol", "Road" },
	{ "Qızıl", "Gold" },
	{ "Partiya", "Party" },
	{ "Xəstəxana", "Hospital" },
	{ "Tərəvəz", "Vegetable" },
	{ "Dünya", "World" },
	{ "Məktəb", "School" },
	{ "Heyvan", "Animal" },
	{ "Göl", "Lake" },
	{ "Paltar", "Clothes" },
	{ "Qələmlik", " Pencilcase" },
	{ "Sənət", "Art" },
	{ "Şəkil", "Picture" },
	{ "Telefon", "Telephone" },
	{ "Market", "Market" },
	{ "Şirinlik", "Sweetness" },
	{ "it", "dog" },
	{ "pişik", "cat" },
	{ "quş", "bird" },
	{ "at", "horse" },
	{ "inək", "cow" },
	{ "qoyun", "sheep" },
	{ "keçi", "goat" },
	{ "şir", "lion" },
	{ "pələng", "tiger" },
	{ "fil", "elephant" },
	{ "ilan", "snake" },
	{ "həşərat", "insect" },
	{ "kəpənək", "butterfly" },
	{ "arı", "bee" },
	{ "qarışqa", "ant" },
	{ "ağcaqanad", "mosquito" },
	{ "kompüter", "computer" },
	{ "kamera", "camera" },
	{ "radiyo", "radio" },
	{ "notbuk", "laptop" },
	{ "klavyatura", "keyboard" },
	{ "siçan", "mouse" },
	{ "internet", "internet" },
	{ "veb sayt", "website" },
	{ "e-poçt", "email" },
	{ "oyun", "game" },
	{ "musiqi", "music" },
	{ "video", "video" },
	{ "film", "film" },
	{ "xəbər", "news" },
	{ "mahnı", "song" },
	{ "rəqs", "dance" },
	{ "poeziya", "poetry" },
	{ "roman", "novel" },
	{ "hekayə", "story" },
	{ "aktyor", "actor" },
	{ "aktrisa", "actress" },
	{ "müğənni", "singer" },
	{ "rəssam", "painter" },
	{ "heykəltəraş", "sculptor" },
	{ "şair", "poet" },
	{ "yazıçı", "writer" },
	{ "teatr", "theater" },
	{ "muzey", "museum" },
	{ "konsertdə", "concert" },
	{ "sərgi", "exhibition" },
	{ "şənlik", "festival" },
	{ "ad günü", "birthday" },
	{ "toy", "wedding" },
	{ "dəfn, dəfn mərasimi", "funeral" },
	{ "körpə", "baby" },
	{ "uşaq", "child" },
	{ "yeniyetmə", "teenager" },
	{ "yetkin", "adult" },
	{ "ahıl", "elderly" },
	{ "ayaqqabı", "shoe" },
	{ "papaq", "hat" },
	{ "palto, pencək", "coat" },
	{ "yubka, ətək", "skirt" },
	{ "şalvar", "pants" },
	{ "bluza", "blouse" },
	{ "çorab", "socks" },
	{ "çəkmə", "boots" },
	{ "kubok", "mug" },
	{ "boşqab", "plate" },
	{ "çəngəl", "fork" },
	{ "bıçaq", "knife" },
	{ "qaşıq", "spoon" },
	{ "divan", "sofa" },
	{ "lampa", "lamp" },
	{ "qapı", "door" },
	{ "dam", "roof" },
	{ "divar", "wall" },
	{ "mərtəbə", "floor" },
	{ "qələm", "pencil" },
	{ "saat", "clock" },
	{ "soyuducu", "refrigerator" },
	{ "peç, soba", "oven" },
	{ "mikrodalğalı soba", "microwave" },
	{ "qabyuyan", "dishwasher" },
	{ "toster", "toaster" },
	{ "velisoped", "bike" },
	{ "avtobus", "bus" },
	{ "qatar", "train" },
	{ "təyyarə", "plane" },
	{ "qayıq", "boat" },
	{ "xəstəxana", "hospital" },
	{ "məktəb", "school" },
	{ "ofisdə", "office" },
	{ "mağaza", "store" },
	{ "restoran", "restaurant" },
	{ "kilsə", "church" },
	{ "məbəd", "temple" },
	{ "heyvanxana", "zoo" },
	{ "akvarium", "aquarium" },
	{ "dağlar", "mountains" },
	{ "dərə, vadi", "valley" },
	{ "çöl", "prairie" },
	{ "təpə", "hill" },
	{ "kanyon", "canyon" },
	{ "vulkan", "volcano" },
	{ "okean", "ocean" },
	{ "gölməçə", "pond" },
	{ "axın", "stream" },
	{ "bahar", "spring" },
	{ "şəlalə", "waterfall" },
	{ "mağara", "cave" },
	{ "dune", "dune" },
	{ "çəmən", "meadow" },
	{ "meyvə bağı", "orchard" },
	{ "üzümbağı", "vineyard" },
	{ "ferma", "farm" },
	{ "kənd", "village" },
	{ "şəhər", "town" },
	{ "ölkə", "country" },
	{ "qitə", "continent" },
	{ "torpaq", "earth" },
	{ "ay", "moon" },
	{ "günəş", "sun" },
	{ "ulduz", "star" },
	{ "qalaktika", "galaxy" },
	{ "kainat", "universe" },
	{ "səhər", "morning" },
	{ "axşam", "evening" },
	{ "günorta", "afternoon" },
	{ "gecə", "night" },
	{ "Günəşin doğuşu", "sunrise" },
	{ "Gun batisi", "sunset" },
	{ "gecə yarısı", "midnight" },
	{ "klinika", "clinic" },
	{ "aptek", "pharmacy" },
	{ "həkim", "doctor" },
	{ "tibb bacısı", "nurse" },
	{ "dərman", "medicine" },
	{ "xəstə", "patient" },
	{ "sağlamlıq", "health" },
	{ "xəstəlik", "illness" },
	{ "zədə", "injury" },
	{ "ağrı", "pain" },
	{ "müalicə", "treatment" },
	{ "sağalma", "recovery" },
	{ "qəbul", "appointment" },
	{ "universitet", "university" },
	{ "tələbə", "student" },
	{ "müəllim", "teacher" },
	{ "sinif otağı", "classroom" },
	{ "ev tapşırığı", "homework" },
	{ "imtahan", "exam" },
	{ "degree", "dərəcə" },
	{ "diploma", "diploma" },
	{ "education", "təhsil" },
	{ "lesson", "dərs" },
	{ "question", "sual" },
	{ "answer", "cavab" },
	{ "subject", "fənn" },
	{ "office", "ofis" },
	{ "meeting", "toplantı" },
	{ "project", "layihə" },
}

return wordlist
