local wordlist = {

	{ "pəncərə", "window" },
	{ "əlaqə", "relationship" },
	{ "achar", "key" },
	{ "güzgü", "mirror" },
	{ "yastiq", "pillow" },
	{ "vergi", "tax" },
	{ "maaş", "salary" },
	{ "hökumət", "gouverment" },
	{ "düz gedin", "go straight" },
	{ "otaq", "room" },
	{ "insan", "human" },
	{ "ruh", "spirit" },
	{ "ola bilər", "maybe" },
	{ "dəftər", "notebook" },
	{ "kino", "movie" },
	{ "sakit okean", "pacific ocean" },
	{ "kilsə", "church" },
	{ "hökumət", "gouverment" },
	{ "Gün", "Day" },
	{ "Kitab", "Book" },
	{ "Masa", "Table" },
	{ "Qapı", "Door" },
	{ "Təyyarə", "Plane" },
	{ "Qurşu", "Bread" },
	{ "Qələm", "Pen" },
	{ "Uşaq", "Child" },
	{ "Bağ", "Garden" },
	{ "Şəhər", "City" },
	{ "Meyvə", "Fruit" },
	{ "Dərə", "Valley" },
	{ "Yol", "Road" },
	{ "Qızıl", "Gold" },
	{ "Partiya", "Party" },
	{ "Xəstəxana", "Hospital" },
	{ "Tərəvəz", "Vegetable" },
	{ "Dünya", "World" },
	{ "Məktəb", "School" },
	{ "Heyvan", "Animal" },
	{ "Göl", "Lake" },
	{ "Paltar", "Clothes" },
	{ "Qələmlik", " Pencilcase" },
	{ "Sənət", "Art" },
	{ "Şəkil", "Picture" },
	{ "Telefon", "Telephone" },
	{ "Market", "Market" },
	{ "Şirinlik", "Sweetness" },
}

return wordlist
