local wordlist = {
	{ "Bütün", "whole" },
	{ "Haqqında", "about" },
	{ "Onda", "then" },
	{ "Vəhşi", "wild" },
	{ "Sakit", "calm" },
	{ "Tez", "early" },
	{ "Gec", "late" },
	{ "Soyuq", "cold" },
	{ "Isti", "hot" },
	{ "Pulsuz", "free" },
	{ "Qürurlu", "proud" },
	{ "Köhnə", "old" },
	{ "Gözəl", "Beautiful" },
	{ "Yaxşı", "Good" },
	{ "Pis", "Bad" },
	{ "Yeni", "New" },
	{ "Qara", "Black" },
	{ "Ağ", "White" },
	{ "Böyük", "Big" },
	{ "Ucuz", "Cheap" },
	{ "Bahalı", "Expensive" },
	{ "Yaxın", "Near" },
	{ "Uzak", "Far" },
	{ "Qırmızı", "Red" },
	{ "Mavi", "Blue" },
	{ "Qaranlıq", "Dark" },
	{ "Yüngül", "Light" },
	{ "Yaxın", "Close" },
	{ "Uzaq", "Distant" },
	{ "Qeyri-adi", "Unusual" },
}

return wordlist
