local wordlist = {
	{ "bütün", "whole" },
	{ "haqqında", "about" },
	{ "onda", "then" },
	{ "vəhşi", "wild" },
	{ "sakit", "calm" },
	{ "tez", "early" },
	{ "gec", "late" },
	{ "soyuq", "cold" },
	{ "isti", "hot" },
	{ "pulsuz", "free" },
	{ "qürurlu", "proud" },
	{ "köhnə", "old" },
	{ "Gözəl", "Beautiful" },
	{ "Yaxşı", "Good" },
	{ "Pis", "Bad" },
	{ "Yeni", "New" },
	{ "Qara", "Black" },
	{ "Ağ", "White" },
	{ "Əsas", "Main" },
	{ "Böyük", "Big" },
	{ "Ucuz", "Cheap" },
	{ "bahalı", "Expensive" },
	{ "Yaxın", "Near" },
	{ "Uzak", "Far" },
	{ "Qırmızı", "Red" },
	{ "Mavi", "Blue" },
	{ "Qaranlıq", "Dark" },
	{ "Yüngül", "Light" },
	{ "Yaxın", "Close" },
	{ "Uzaq", "Distant" },
	{ "Qeyri-adi", "Unusual" },
}

return wordlist
