local wordlist = {
   { "bütün", "whole" },
   { "haqqında", "about" },
   { "vəhşi", "wild" },
   { "doğurdan", "really" },
   { "sakit", "calm" },
   { "tez", "early" },
   { "gec", "late" },
   { "soyuq", "cold" },
   { "isti", "hot" },
   { "pulsuz", "free" },
   { "qürur", "proud" },
   { "köhnə", "old" },
   { "Gözəl", "Beautiful" },
   { "Yaxşı", "Good" },
   { "Pis", "Bad" },
   { "Yeni", "New" },
   { "Qara", "Black" },
   { "Ağ", "White" },
   { "Əsas", "Main" },
   { "Böyük", "Big" },
   { "Ucuz", "Cheap" },
   { "bahalı", "Expensive" },
   { "Yaxın", "Near" },
   { "Qırmızı", "Red" },
   { "Mavi", "Blue" },
   { "Uzaq", "Distant" },
   { "Yüngül", "Light" },
   { "Qeyri-adi", "Unusual" },
}

return wordlist
