

wordlist = {
   {"Kino","Movie"},
   {"Üğurlar","Good Luck" },
   {"Xoş gördük","Good to see you" },
   {"Xeyr","No" },
   {"Kimi","Who" },
   {"Dəftər","Notebook" },
   {"Kilsə","Church" },
   {"Edec","Do" },
   {"Ola bilər","Maybe" },
   {"Var","There is" },
   {"Hara","Where" },
   {"Hansı","Which" },
   {"Sənin nə yaşin var","How old are you" },
   {"Tez","Early/Fast" },
   {"Gec","Late" },
   {"Təzliklə","Soon" },
   {"Soyuq","Cold" },
   {"Isti","Hot" },
   {"Yemək","Food" },
   {"Sənin adın nədir","whats your name" },
   {"mənim adım","my name is" },
   {"şad oldum","nice to meet you" },
   {"necəsən","how are you" },
   {"səni səviram","I love you" },
   {"salam","hello" },
   {"minoş","Cute" },
   {"balam","My baby" },
   {"Yaxşıyam","I am fine" },
   {"bəli","yes" },
   {"çox sagol","Thank you" },
   {"helelik","goodbye" },
   {"tualet hardadir","where is the toilet" },
   {"duz gedın","go straight" },
   {"sola don","turn left" },
   {"sağa don","turn right" },
   {"avtobus və qatar"," bus and train" },
   {"sabahın xeyir","good morning" },
   {"öpürəm sən","I kiss you" },
   {"Bütun","Whole" },
   {"Qürur","Proud" },
 }


 return {
 wordlist,
 }
